export const WASTE_CLASSIFICATION = [
    {
        id: 0,
        label: 'PET병',
        category1: '생활폐기물',
        category2: '재활용',
        category3: 'PET병',
    },
    {
        id: 1,
        label: 'tv/텔레비전',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: 'tv/텔레비전',
    },
    {
        id: 2,
        label: '가방',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '가방',
    },
    {
        id: 3,
        label: '가스레인지',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '가스레인지',
    },
    {
        id: 4,
        label: '가습기/제습기/공기청정기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '가습기/제습기/공기청정기',
    },
    {
        id: 5,
        label: '간판',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '간판',
    },
    {
        id: 6,
        label: '감시카메라',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '감시카메라',
    },
    {
        id: 7,
        label: '거울',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '거울',
    },
    {
        id: 8,
        label: '건조대',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '건조대',
    },
    {
        id: 9,
        label: '고무통',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '고무통',
    },
    {
        id: 10,
        label: '고철류',
        category1: '생활폐기물',
        category2: '재활용',
        category3: '고철류',
    },
    {
        id: 11,
        label: '골프채, 낚시대, 등산스틱',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '골프채, 낚시대, 등산스틱',
    },
    {
        id: 12,
        label: '공유기/모뎀',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '공유기/모뎀',
    },
    {
        id: 13,
        label: '금고',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '금고',
    },
    {
        id: 14,
        label: '금속캔',
        category1: '생활폐기물',
        category2: '재활용',
        category3: '금속캔',
    },
    {
        id: 15,
        label: '난방기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '난방기',
    },
    {
        id: 16,
        label: '냉장고',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '냉장고',
    },
    {
        id: 17,
        label: '다리미',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '다리미',
    },
    {
        id: 18,
        label: '다리미판',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '다리미판',
    },
    {
        id: 19,
        label: '도마',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '도마',
    },
    {
        id: 20,
        label: '돗자리',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '돗자리',
    },
    {
        id: 21,
        label: '라켓',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '라켓',
    },
    {
        id: 22,
        label: '매트리스',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '매트리스',
    },
    {
        id: 23,
        label: '모니터',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '모니터',
    },
    {
        id: 24,
        label: '목재류',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '목재류',
    },
    {
        id: 25,
        label: '문짝',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '문짝',
    },
    {
        id: 26,
        label: '믹서기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '믹서기',
    },
    {
        id: 27,
        label: '바둑판',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '바둑판',
    },
    {
        id: 28,
        label: '반려동물용품',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '반려동물용품',
    },
    {
        id: 29,
        label: '받침대',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '받침대',
    },
    {
        id: 30,
        label: '밥상',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '밥상',
    },
    {
        id: 31,
        label: '방충망',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '방충망',
    },
    {
        id: 32,
        label: '배기후드',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '배기후드',
    },
    {
        id: 33,
        label: '변기',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '변기',
    },
    {
        id: 34,
        label: '보관함(공간박스)',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '보관함(공간박스)',
    },
    {
        id: 35,
        label: '보일러',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '보일러',
    },
    {
        id: 36,
        label: '복사기/프린터/스캐너/팩시밀리',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '복사기/프린터/스캐너/팩시밀리',
    },
    {
        id: 37,
        label: '블라인드',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '블라인드',
    },
    {
        id: 38,
        label: '비닐류',
        category1: '생활폐기물',
        category2: '재활용',
        category3: '비닐류',
    },
    {
        id: 39,
        label: '비데',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '비데',
    },
    {
        id: 40,
        label: '빈페인트통',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '빈페인트통',
    },
    {
        id: 41,
        label: '빔프로젝터',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '빔프로젝터',
    },
    {
        id: 42,
        label: '서랍장',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '서랍장',
    },
    {
        id: 43,
        label: '선풍기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '선풍기',
    },
    {
        id: 44,
        label: '세단기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '세단기',
    },
    {
        id: 45,
        label: '세면대',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '세면대',
    },
    {
        id: 46,
        label: '세탁기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '세탁기',
    },
    {
        id: 47,
        label: '소파',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '소파',
    },
    {
        id: 48,
        label: '소화기',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '소화기',
    },
    {
        id: 49,
        label: '수도호스',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '수도호스',
    },
    {
        id: 50,
        label: '수조/어항',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '수조/어항',
    },
    {
        id: 51,
        label: '스노우보드/스키',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '스노우보드/스키',
    },
    {
        id: 52,
        label: '시계',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '시계',
    },
    {
        id: 53,
        label: '식기세척기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '식기세척기',
    },
    {
        id: 54,
        label: '식품건조기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '식품건조기',
    },
    {
        id: 55,
        label: '싱크대',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '싱크대',
    },
    {
        id: 56,
        label: '쌀통',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '쌀통',
    },
    {
        id: 57,
        label: '쓰레기통',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '쓰레기통',
    },
    {
        id: 58,
        label: '아이스박스',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '아이스박스',
    },
    {
        id: 59,
        label: '아일랜드/대리석테이블',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '아일랜드/대리석테이블',
    },
    {
        id: 60,
        label: '안마의자',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '안마의자',
    },
    {
        id: 61,
        label: '액자',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '액자',
    },
    {
        id: 62,
        label: '에어컨',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '에어컨',
    },
    {
        id: 63,
        label: '오디오',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '오디오',
    },
    {
        id: 64,
        label: '옷걸이(스탠드형)',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '옷걸이(스탠드형)',
    },
    {
        id: 65,
        label: '옷장',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '옷장',
    },
    {
        id: 66,
        label: '욕조',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '욕조',
    },
    {
        id: 67,
        label: '운동기구(가전류)',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '운동기구(가전류)',
    },
    {
        id: 68,
        label: '운동기구(비가전류)',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '운동기구(비가전류)',
    },
    {
        id: 69,
        label: '유모차',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '유모차',
    },
    {
        id: 70,
        label: '유아용자동차',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '유아용자동차',
    },
    {
        id: 71,
        label: '유아용품',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '유아용품',
    },
    {
        id: 72,
        label: '음식물처리기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '음식물처리기',
    },
    {
        id: 73,
        label: '의료보조기기',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '의료보조기기',
    },
    {
        id: 74,
        label: '의자',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '의자',
    },
    {
        id: 75,
        label: '이불',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '이불',
    },
    {
        id: 76,
        label: '인형',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '인형',
    },
    {
        id: 77,
        label: '입간판',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '입간판',
    },
    {
        id: 78,
        label: '자동판매기',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '자동판매기',
    },
    {
        id: 79,
        label: '자전거',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '자전거',
    },
    {
        id: 80,
        label: '장난감류',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '장난감류',
    },
    {
        id: 81,
        label: '장식장',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '장식장',
    },
    {
        id: 82,
        label: '재봉틀',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '재봉틀',
    },
    {
        id: 83,
        label: '전기/옥/온수/자석매트',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '전기/옥/온수/자석매트',
    },
    {
        id: 84,
        label: '전기밥솥',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '전기밥솥',
    },
    {
        id: 85,
        label: '전기안마기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '전기안마기',
    },
    {
        id: 86,
        label: '전기포트',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '전기포트',
    },
    {
        id: 87,
        label: '전기프라이팬',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '전기프라이팬',
    },
    {
        id: 88,
        label: '전자레인지/오븐',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '전자레인지/오븐',
    },
    {
        id: 89,
        label: '정수기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '정수기',
    },
    {
        id: 90,
        label: '조명기구',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '조명기구',
    },
    {
        id: 91,
        label: '조명폐기물',
        category1: '생활폐기물',
        category2: '재활용',
        category3: '조명폐기물',
    },
    {
        id: 92,
        label: '족욕기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '족욕기',
    },
    {
        id: 93,
        label: '찬장',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '찬장',
    },
    {
        id: 94,
        label: '창문',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '창문',
    },
    {
        id: 95,
        label: '책상',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '책상',
    },
    {
        id: 96,
        label: '책장',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '책장',
    },
    {
        id: 97,
        label: '청소기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '청소기',
    },
    {
        id: 98,
        label: '칠판',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '칠판',
    },
    {
        id: 99,
        label: '침대(프레임/일체형)',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '침대(프레임/일체형)',
    },
    {
        id: 100,
        label: '카페트',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '카페트',
    },
    {
        id: 101,
        label: '칸막이',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '칸막이',
    },
    {
        id: 102,
        label: '캐비닛',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '캐비닛',
    },
    {
        id: 103,
        label: '커피메이커',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '커피메이커',
    },
    {
        id: 104,
        label: '컴퓨터',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '컴퓨터',
    },
    {
        id: 105,
        label: '키보드',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '키보드',
    },
    {
        id: 106,
        label: '킥보드',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '킥보드',
    },
    {
        id: 107,
        label: '타이어',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '타이어',
    },
    {
        id: 108,
        label: '탁구대',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '탁구대',
    },
    {
        id: 109,
        label: '탈수기',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '탈수기',
    },
    {
        id: 110,
        label: '테이블',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '테이블',
    },
    {
        id: 111,
        label: '텐트/타프',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '텐트/타프',
    },
    {
        id: 112,
        label: '토스터기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '토스터기',
    },
    {
        id: 113,
        label: '튀김기(업소용)',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '튀김기(업소용)',
    },
    {
        id: 114,
        label: '판유리',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '판유리',
    },
    {
        id: 115,
        label: '폐유리병류',
        category1: '생활폐기물',
        category2: '재활용',
        category3: '폐유리병류',
    },
    {
        id: 116,
        label: '폐의류',
        category1: '생활폐기물',
        category2: '재활용',
        category3: '폐의류',
    },
    {
        id: 117,
        label: '폐전지류',
        category1: '생활폐기물',
        category2: '재활용',
        category3: '폐전지류',
    },
    {
        id: 118,
        label: '폐지류',
        category1: '생활폐기물',
        category2: '재활용',
        category3: '폐지류',
    },
    {
        id: 119,
        label: '피아노/오르간',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '피아노/오르간',
    },
    {
        id: 120,
        label: '항아리',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '항아리',
    },
    {
        id: 121,
        label: '헤어드라이기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '헤어드라이기',
    },
    {
        id: 122,
        label: '화분',
        category1: '대형 폐기물',
        category2: '생활용품류',
        category3: '화분',
    },
    {
        id: 123,
        label: '화장대',
        category1: '대형 폐기물',
        category2: '가구류',
        category3: '화장대',
    },
    {
        id: 124,
        label: '화환',
        category1: '대형 폐기물',
        category2: '기타',
        category3: '화환',
    },
    {
        id: 125,
        label: '환풍기',
        category1: '대형 폐기물',
        category2: '가전제품류',
        category3: '환풍기',
    },
];
