export const INIT_STATE = {
  CHECKING: "CHECKING",
  NETWORK_ERROR: "NETWORK_ERROR",
  PERMISSION_REQUIRED: "PERMISSION_REQUIRED",
  AUTH_ERROR: "AUTH_ERROR",
  FORCE_UPDATE: "FORCE_UPDATE",
  READY: "READY",
} as const;